CREATE TRIGGER [RestarStock]
	ON [dbo].[PEDIDO]
	AFTER INSERT
	AS
	BEGIN
	DECLARE
	@Cantidad INT,
	@OldCant INT

	SELECT @Cantidad = CANTIDADPEDIDO FROM Inserted

	SELECT @OldCant=(SELECT CANTIDADPRODUCTO FROM dbo.STOCK WHERE CODIGOPRODUCTO = (SELECT CODIGOPRODUCTO FROM Inserted))

	
	UPDATE dbo.STOCK SET CANTIDADPRODUCTO=@OldCant-@Cantidad WHERE dbo.STOCK.CODIGOPRODUCTO = (Select CODIGOPRODUCTO FROM inserted)
	END
