//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ARTESANO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTESANO()
        {
            this.STOCK = new HashSet<STOCK>();
        }
        [Required]
        [Display(Name ="Código de artesano")]
        public int CODIGOARTESANO { get; set; }
        [Required]
        [Display(Name = "Dirección")]
        public Nullable<int> CODIGODIRECCION { get; set; }
        [Required]
        [Display(Name = "Disciplina")]
        public Nullable<int> CODIGODISCIPLINA { get; set; }
        [Required]
        [StringLength(10, MinimumLength = 10)]
        [Display(Name = "Cédula")]
        public string CI_RUC_RISE { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string NOMBREARTESANO { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string APELLIDOARTESANO { get; set; }
        [Required]
        [Display(Name = "Fecha de nacimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHANACIMIENTO { get; set; }
        [Required]
        [Display(Name = "Número de afiliación")]
        public int NUMEROAFILIACION { get; set; }
        [Required]
        [Display(Name = "Barrio de trabajo")]
        public string BARRIOARTESANO { get; set; }
        [StringLength(10, MinimumLength = 10)]
        [Display(Name = "Teléfono taller")]
        public string TELEFONOTALLERARTESANO { get; set; }
        [StringLength(10, MinimumLength = 10)]
        [Display(Name = "Teléfono domicilio")]
        public string TELEFONODOMICILIOARTESANO { get; set; }
        [StringLength(10, MinimumLength = 10)]
        [Display(Name = "Teléfono personal")]
        public string TELEFONOPERSONALARTESANO { get; set; }
        [Display(Name = "Correo")]
        [EmailAddress(ErrorMessage = "Direccion de correo electronico invalida")]
        [DataType(DataType.EmailAddress)]
        public string CORREOARTESANO { get; set; }
        [Display(Name = "Razón social")]
        public string RAZONSOCIAL { get; set; }
        [Display(Name = "Actividad del negocio")]
        public string ACTIVIDADNEGOCIO { get; set; }
        [Display(Name = "Reseña histórica")]
        public string RESENAHISTORICAMARCA { get; set; }
        [Display(Name = "Logo de la marca")]
        public byte[] LOGOMARCA { get; set; }
        [Display(Name = "Acuerdo interministerial")]
        public string ACUERTOINTERMINISTERIAL { get; set; }
        [Display(Name = "Patente municipal")]
        public string PATENTEMUNICIPAL { get; set; }
        public virtual DISCIPLINA DISCIPLINA { get; set; }
        public virtual DIRECCION DIRECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCK { get; set; }
    }
}
