//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCION()
        {
            this.ARTESANO = new HashSet<ARTESANO>();
        }
        [Required]
        [Display(Name = "Código de dirección")]
        public int CODIGODIRECCION { get; set; }
        [Required]
        [Display(Name = "Sector")]
        public string SECTORDIRECCION { get; set; }
        [Required]
        [Display(Name = "Barrio")]
        public string BARRIODIRECCION { get; set; }
        [Required]
        [Display(Name = "Calle Principal")]
        public string CALLEPRINCIPAL { get; set; }
        [Required]
        [Display(Name = "Calle secundaria")]
        public string CALLESECUNDARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTESANO> ARTESANO { get; set; }
    }
}
