//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.STOCK = new HashSet<STOCK>();
        }
        [Required]
        [Display(Name = "código de producto")]
        public int CODIGOPRODUCTO { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string NOMBREPRODUCTO { get; set; }
        [Display(Name = "Foto")]
        public byte[] FOTOPRODUCTO { get; set; }
        [Required]
        [Display(Name = "Precio")]
        public double PRECIOPRODUCTO { get; set; }
        public HttpPostedFileBase imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCK { get; set; }
    }
}
